apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-app
  template:
    metadata:
      labels:
        app: streaming-app
    spec:
      containers:
      - name: streaming-app
        image: koreapower98/wed2:test
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          request:
            cpu: "0.2"
            memory: "256Mi"
        ports:
          - containerPort: 3001
        nodeSelector:
          node-role.kubernetes.io/worker: ""
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: rds-secret
                key: host
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: rds-secret
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rds-secret
                key: password
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: rds-secret
                key: database
        volumeMounts:
        - name: s3-bucket
          mountPath: /mnt/s3bucket
      volumes:
      - name: s3-bucket
        hostPath:
          path: /mnt/s3bucket
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: streaming-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer # 매니저(manager) 노드에 배포
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: streaming-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streaming-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
